version: '3.5'

services:

  postgis:
    container_name: postgis
    image: ghcr.io/mborne/postgis:14-3
    build: img/14-3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis-data:
    name: postgis-data-14

networks:
  default:
    name: devbox

