version: '3.5'

services:

  postgis:
    container_name: postgis
    image: mborne/postgis:10.5-2.4
    build: .
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis-data:
    name: postgis-data

networks:
  default:
    external:
      name: devbox
